services:
    easy_admin_popup.listener.crud_flashbag:
        class: A5sys\EasyAdminPopupBundle\Listener\CrudFlashbagListener
        arguments:
            - "@session"
            - "@translator"
        tags:
            - { name: kernel.event_listener, event: "easy_admin.post_persist", method: onPostPersist }
            - { name: kernel.event_listener, event: "easy_admin.post_update", method: onPostUpdate }
            - { name: kernel.event_listener, event: "easy_admin.post_remove", method: onPostRemove }
    easy_admin_popup.translation.entity_extractor:
        class: "A5sys\\EasyAdminPopupBundle\\Translation\\EntityExtractor"
        arguments:
            - "%easyadmin.config%"
            - "EasyAdminBundle"
            - "@easyadmin.translation.entity_translation"
        tags:
            -  { name: jms_translation.extractor, alias: "adminbundle_translation_entity_extractor" }
    easyadminpopup.twig.extension:
        class: "A5sys\\EasyAdminPopupBundle\\Twig\\EasyAdminPopupTwigExtension"
        arguments:
            - "%easy_admin_popup.layout%"
        tags:
            - { name: twig.extension }